### ISSUE TITLE
[WIP] 2.0

### ISSUE THREAD

**Issue by zloirock** [zloirock/core-js#137]
- [x] Add implementations and fixes `ArrayBuffer`, `DataView`, all typed arrays constructors with all static and prototype methods. Really hard point. #90
- [x] Improve collections polyfills - `O(1)` and prevent possible leaking with frozen keys, correct observable state for object keys, #134
- [x] Add `{keys, values, entries, @@iterator}` methods to all DOM collections which should have [iterable interface](https://heycam.github.io/webidl/#idl-iterable) or should be [inherited from `Array`](https://heycam.github.io/webidl/#LegacyArrayClass)
- [x] Add basic support [`rejectionHandled` event](https://nodejs.org/api/process.html#process_event_rejectionhandled) / [`onrejectionhandled` handler](https://developer.mozilla.org/en-US/docs/Web/API/Window/onrejectionhandled) to the `Promise` polyfill
- [x] Rename `String#{padLeft, padRight}` -> `String#{padStart, padEnd}`, [proposal](https://github.com/tc39/proposal-string-pad-start-end), [November TC39 meeting](https://github.com/rwaldron/tc39-notes/tree/master/es7/2015-11/nov-17.md#conclusionresolution-2) (they want to rename it on each meeting?O_o), #132
- [x] Add `String#{trimStart, trimEnd}` as aliases for `String#{trimLeft, trimRight}`, [proposal](https://github.com/sebmarkbage/ecmascript-string-left-right-trim), [November TC39 meeting](https://github.com/rwaldron/tc39-notes/tree/master/es7/2015-11/nov-17.md#conclusionresolution-2)
- [x] Add `System.global`, [proposal](https://github.com/tc39/proposal-global), [November TC39 meeting](https://github.com/rwaldron/tc39-notes/tree/master/es7/2015-11/nov-19.md#systemglobal-jhd)
- [x] Add `Error.isError`, [proposal](https://github.com/ljharb/proposal-is-error), [November TC39 meeting](https://github.com/rwaldron/tc39-notes/tree/master/es7/2015-11/nov-19.md#jhd-erroriserror)
- [x] Remove usage `@@species` from `Promise.{all, race}`, [November TC39 meeting](https://github.com/rwaldron/tc39-notes/tree/master/es7/2015-11/nov-18.md#conclusionresolution-2)
- [x] Check changes by [meeting notes](https://github.com/rwaldron/tc39-notes/tree/master/es7/2015-11)
- [x] Add `Math.{iaddh, isubh, imulh, umulh}`, [proposal](https://gist.github.com/BrendanEich/4294d5c212a6d2254703)
- [x] Move `RegExp.escape` from `es7` to non-standard `core` namespace, [July TC39 meeting](https://github.com/rwaldron/tc39-notes/blob/master/es7/2015-07/july-28.md#62-regexpescape) - too slow, but it's condition of stability, #116
- [x] Add annex B HTML methods - ugly, but also [the part of the spec](http://www.ecma-international.org/ecma-262/6.0/#sec-string.prototype.anchor)
- [x] Add little fix for `Date#toString` - `new Date(NaN).toString()` [should be `'Invalid Date'`](http://www.ecma-international.org/ecma-262/6.0/#sec-todatestring)
- [x] Remove `core.log` module
- [x] Remove Mozilla `Array` generics - [deprecated and will be removed from FF](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#Array_generic_methods), looks like [strawman](http://wiki.ecmascript.org/doku.php?id=strawman:array_statics) is dead. Available [alternative shim](https://github.com/plusdude/array-generics).
- [x] Change `$` prefix for internal modules file names because (holy shit!) Team Foundation Server does not support it, #129 (please, don't use `core-js` internal modules in your scripts!)
- [x] Move custom build from external scripts to the separate package for preventing problems with dependencies, some changes in that API
- [x] Add entry points for virtual methods
- [x] Add entry points for stages proposals

[...and if the situation does not change, it can be the last big release :(](https://github.com/zloirock/core-js/issues/139)

**Comment by zloirock** [comment]
@Arnavion can you confirm [the list of required DOM collections](https://github.com/zloirock/core-js/blob/master/modules/web.dom.iterable.js#L13-L14)? Current list based on [this your issue and comments](https://github.com/Microsoft/TypeScript/issues/2695). I'm not an expert in W3C and WHATWG specs and currently have no time to explore it.

**Comment by zloirock** [comment]
@guybedford `System.global` will not have a conflict with SystemJS?

**Comment by zloirock** [comment]
Any more ideas about this release?

**Comment by guybedford** [comment]
@zloirock thanks for the ping. `System.global` is actually already defined by SystemJS. Am I right in thinking that https://github.com/zloirock/core-js/blob/master/modules/_export.js#L21 is non-destructive so this should work out ok?

We do need to move to `System.loader` instead of treating `System` as the loader though anyway as soon as the WhatWG spec is stable enough to switch.

**Comment by zloirock** [comment]
@guybedford previously available `System` object will not be overridden.  Main here - the second your point required additional feature detection.

**Comment by Arnavion** [comment]
Sorry, I haven't been keeping up with this space. @SaschaNaz or users of core-js may have something to say.

BTW note the list in my comment you linked was built from experimenting with Nightly and is not based off spec(s). For example [MimeTypeArray](https://html.spec.whatwg.org/multipage/webappapis.html#mimetypearray) doesn't seem to be iterable. It's a mess...

Maybe just expect everyone to use `Array.from` ...

**Comment by SaschaNaz** [comment]
I had some time to quickly explore spec documents.

Yes:

1. MediaList, StyleSheetList, and CSSRuleList are iterable as they are `ArrayClass`es according to the [latest CSSOM working draft](http://www.w3.org/TR/2013/WD-cssom-20131205/) and the latest editor's draft.
2. NodeList and DOMTokenList are iterable according to the [W3C DOM4 final spec](http://www.w3.org/TR/2015/REC-dom-20151119/#interface-htmlcollection)

No:

1. DOMStringList is not iterable and deprecated according to [W3C DOM4 final spec](http://www.w3.org/TR/2015/REC-dom-20151119/#interface-htmlcollection)
2. HTMLCollection is not iterable according to the DOM4 spec.
3. NamedNodeMap is not iterable according to the W3C and [WHATWG DOM4](https://dom.spec.whatwg.org/#namednodemap) docs
4. FileList is not iterable according to [File API working draft](http://www.w3.org/TR/2015/WD-FileAPI-20150421/#dfn-filelist)
5. PluginArray and Plugin are not iterable according to [HTML5](http://www.w3.org/TR/2014/REC-html5-20141028/webappapis.html#plugins-0) and [HTML5.1 draft](http://www.w3.org/TR/2015/WD-html51-20151008/webappapis.html#plugins-2) specs
6. TouchList is not iterable according to [Touch Events Level 2 spec](https://w3c.github.io/touch-events/#touchlist-interface)

**Comment by zloirock** [comment]
@Arnavion @SaschaNaz thanks for replies.

> `HTMLCollection` is not iterable according to the DOM4 spec.

Interesting because iterable `HTMLCollection` - very frequent issue (#37, #68, in other trackers and chats...). If most DOM collections not required - maybe makes no sense replace `Symbol` in Chromium 38-40, just patch some methods, need to test it.

Some days I will not change this list, maybe someone else clarify this.

**Comment by zloirock** [comment]
Done.
