### ISSUE TITLE
[WIP] 1.0

### ISSUE THREAD

**Issue by zloirock** [zloirock/core-js#83]
- ~~Add [`Observable`](https://github.com/zenparsing/es-observable) if it will be enough stable~~ Awaiting results of [the July TC39 meeting](https://github.com/tc39/agendas/blob/master/2015/07.md) - will be discussed `Observable` API.
- [x] Add logic for well-known symbols if it will be enough fast:
  - [x] `Symbol.match`
  - [x] `Symbol.replace`
  - [x] `Symbol.split`
  - [x] `Symbol.search`
- [x] Actualize and optimize work with iterables:
  - [x] Optimize  `Map`, `Set`, `WeakMap`, `WeakSet` constructors, `Promise.all`, `Promise.race` for default `Array Iterator`.
  - [x] Optimize  `Array.from` for default `Array Iterator`.
  - [x] Add `core.getIteratorMethod` helper.
- [x] Use enumerable properties in shimmed instances - collections, iterators, etc for optimize performance.
- [x] Add support native constructors to [`Reflect.construct`](https://github.com/zloirock/core-js#ecmascript-6-reflect) with 2 arguments.
- [x] Add support native constructors to [`Function#bind`](https://github.com/zloirock/core-js#ecmascript-5) shim with `new`.
- [x] Remove  obsolete `.clear` methods native `Weak`-collections.
- [x] Final cleaning non-standard features:
  - [x] Move `$for` to [separate library](https://github.com/zloirock/forof). This work for syntax - `for-of` loop and comprehensions.
  - [x] Move `Date#{format, formatUTC}` to [separate library](https://github.com/zloirock/dtf). Standard way for this - `ECMA-402`.
  - [x] Remove `Math` methods from `Number.prototype`. Slight sugar for simple `Math` methods calling.
  - [x] Remove `{Array#, Array, Dict}.turn`.
  - [x] Remove `core.global`.
- [x] Use `ToNumber` instead of `ToLength` in [`Number Iterator`](https://github.com/zloirock/core-js#number-iterator), `Array.from(2.5)` will be `[0, 1, 2]` instead of `[0, 1]`.
- [x] Maximum modularity, split to submodules:
  - [x] `es6.reflect`
  - [x] `es6.regexp`
  - [x] `es6.math`
  - [x] `es6.number`
  - [x] `es7.object.to-array`
  - [x] `core.object`
  - [x] `core.string`
  - [x] `core.iter-helpers`
  - [x] Internal modules (`$`, `$.iter`, etc)
- [x] Fix #85 - invalid `Promise` unhandled rejection message in nested `setTimeout`.
- [x] Fix #86 - support FF extensions.
- [x] Fix #89 - behavior `Number` constructor in strange case.
- [x] Add to README "missing polyfills" section.
- [x] Refactoring.

Something else?

**Comment by Awk34** [comment]
"Refactoring" is pretty broad... Are you referencing a specific refactoring task(s)?

**Comment by zloirock** [comment]
@Awk34 nothing concrete - is a task for me inspect all library code and rewrite all required before release. If you have concrete ideas for next release - you can propose them here.

**Comment by andreypopp** [comment]
Probably https://github.com/whatwg/fetch but maybe I misunderstand the scope of core-js?

**Comment by zloirock** [comment]
@andreypopp already opened #25. Possible, but not in this release.
